(function(){/*
 *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
*****************************************************************************/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var e=0;return function(){return e<b.length?{done:!1,value:b[e++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var e="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return e?e.call(b):$jscomp.arrayIterator(b)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,d){b!=Array.prototype&&b!=Object.prototype&&(b[e]=d.value)};
$jscomp.polyfill=function(b,e,d,a){if(e){d=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var c=b[a];c in d||(d[c]={});d=d[c]}b=b[b.length-1];a=d[b];e=e(a);e!=a&&null!=e&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function e(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(b,f){b(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;e.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};e.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var a=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(b){a(b,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var f=a[b];a[b]=null;try{f()}catch(p){this.asyncThrow_(p)}}}this.batch_=null};e.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(f){b.reject(f)}};c.prototype.createResolveAndReject_=
function(){function a(a){return function(p){f||(f=!0,a.call(b,p))}}var b=this,f=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(f){this.reject_(f);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)k.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var k=new e;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var f=this.createResolveAndReject_();try{a.call(b,f.resolve,f.reject)}catch(p){f.reject(p)}};c.prototype.then=function(a,b){function f(a,f){return"function"==typeof a?function(f){try{p(a(f))}catch(x){e(x)}}:
f}var p,e,d=new c(function(a,f){p=a;e=f});this.callWhenSettled_(f(a,p),f(b,e));return d};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function f(){switch(p.state_){case 1:a(p.result_);break;case 2:b(p.result_);break;default:throw Error("Unexpected state: "+p.state_);}}var p=this;null==this.onSettledCallbacks_?k.asyncExecute(f):this.onSettledCallbacks_.push(f)};c.resolve=d;c.reject=function(a){return new c(function(b,f){f(a)})};c.race=function(a){return new c(function(b,
f){for(var p=$jscomp.makeIterator(a),e=p.next();!e.done;e=p.next())d(e.value).callWhenSettled_(b,f)})};c.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?d([]):new c(function(a,e){function p(f){return function(b){c[f]=b;y--;0==y&&a(c)}}var c=[],y=0;do c.push(void 0),y++,d(f.value).callWhenSettled_(p(c.length-1),e),f=b.next();while(!f.done)})};return c},"es6","es3");
$jscomp.checkStringArgs=function(b,e,d){if(null==b)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return b+""};
$jscomp.polyfill("String.prototype.endsWith",function(b){return b?b:function(b,d){var a=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===d&&(d=a.length);d=Math.max(0,Math.min(d|0,a.length));for(var c=b.length;0<c&&0<d;)if(a[--d]!=b[--c])return!1;return 0>=c}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var b={},e=Object.create(new $jscomp.global.Proxy(b,{get:function(d,a,c){return d==b&&"q"==a&&c==e}}));return!0===e.q}catch(d){return!1}};
$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.owns=function(b,e){return Object.prototype.hasOwnProperty.call(b,e)};
$jscomp.polyfill("WeakMap",function(b){function e(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),p=Object.seal({}),c=new b([[a,2],[p,3]]);if(2!=c.get(a)||3!=c.get(p))return!1;c.delete(a);c.set(p,4);return!c.has(a)&&4==c.get(p)}catch(t){return!1}}function d(){}function a(a){if(!$jscomp.owns(a,k)){var b=new d;$jscomp.defineProperty(a,k,{value:b})}}function c(b){var f=Object[b];f&&(Object[b]=function(b){if(b instanceof d)return b;a(b);return f(b)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&
$jscomp.ES6_CONFORMANCE)return b}else if(e())return b;var k="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var r=0,u=function(a){this.id_=(r+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};u.prototype.set=function(b,c){a(b);if(!$jscomp.owns(b,k))throw Error("WeakMap key fail: "+b);b[k][this.id_]=c;return this};u.prototype.get=function(a){return $jscomp.owns(a,k)?a[k][this.id_]:void 0};u.prototype.has=
function(a){return $jscomp.owns(a,k)&&$jscomp.owns(a[k],this.id_)};u.prototype.delete=function(a){return $jscomp.owns(a,k)&&$jscomp.owns(a[k],this.id_)?delete a[k][this.id_]:!1};return u},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){function e(){if($jscomp.ASSUME_NO_NATIVE_MAP||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),c=new b($jscomp.makeIterator([[a,"s"]]));if("s"!=c.get(a)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var e=c.entries(),d=e.next();if(d.done||d.value[0]!=a||"s"!=d.value[1])return!1;d=e.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!e.next().done?!1:!0}catch(g){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(e())return b;$jscomp.initSymbolIterator();var d=new WeakMap,a=function(a){this.data_={};this.head_=r();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};a.prototype.set=function(a,b){a=0===a?0:a;var f=c(this,a);f.list||(f.list=this.data_[f.id]=[]);f.entry?f.entry.value=b:(f.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},f.list.push(f.entry),this.head_.previous.next=f.entry,this.head_.previous=f.entry,this.size++);return this};a.prototype.delete=function(a){a=c(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};a.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=r();this.size=0};a.prototype.has=function(a){return!!c(this,a).entry};
a.prototype.get=function(a){return(a=c(this,a).entry)&&a.value};a.prototype.entries=function(){return k(this,function(a){return[a.key,a.value]})};a.prototype.keys=function(){return k(this,function(a){return a.key})};a.prototype.values=function(){return k(this,function(a){return a.value})};a.prototype.forEach=function(a,b){for(var c=this.entries(),f;!(f=c.next()).done;)f=f.value,a.call(b,f[1],f[0],this)};a.prototype[Symbol.iterator]=a.prototype.entries;var c=function(a,b){var c=b&&typeof b;"object"==
c||"function"==c?d.has(b)?c=d.get(b):(c=""+ ++u,d.set(b,c)):c="p_"+b;var e=a.data_[c];if(e&&$jscomp.owns(a.data_,c))for(a=0;a<e.length;a++){var f=e[a];if(b!==b&&f.key!==f.key||b===f.key)return{id:c,list:e,index:a,entry:f}}return{id:c,list:e,index:-1,entry:void 0}},k=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},r=function(){var a={};return a.previous=
a.next=a.head=a},u=0;return a},"es6","es3");$jscomp.underscoreProtoCanBeSet=function(){var b={a:!0},e={};try{return e.__proto__=b,e.a}catch(d){}return!1};$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(b,e){b.__proto__=e;if(b.__proto__!==e)throw new TypeError(b+" is not extensible");return b}:null;$jscomp.polyfill("Object.setPrototypeOf",function(b){return b||$jscomp.setPrototypeOf},"es6","es5");
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(b,e){for(var d=1;d<arguments.length;d++){var a=arguments[d];if(a)for(var c in a)$jscomp.owns(a,c)&&(b[c]=a[c])}return b};$jscomp.polyfill("Object.assign",function(b){return b||$jscomp.assign},"es6","es3");
(function(b){function e(a){if(d[a])return d[a].exports;var c=d[a]={i:a,l:!1,exports:{}};b[a].call(c.exports,c,c.exports,e);c.l=!0;return c.exports}var d={};e.m=b;e.c=d;e.d=function(a,b,d){e.o(a,b)||Object.defineProperty(a,b,{enumerable:!0,get:d})};e.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};e.t=function(a,b){b&1&&(a=e(a));if(b&8||b&4&&"object"===typeof a&&a&&a.__esModule)return a;
var c=Object.create(null);e.r(c);Object.defineProperty(c,"default",{enumerable:!0,value:a});if(b&2&&"string"!=typeof a)for(var d in a)e.d(c,d,function(b){return a[b]}.bind(null,d));return c};e.n=function(a){var b=a&&a.__esModule?function(){return a["default"]}:function(){return a};e.d(b,"a",b);return b};e.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};e.p="/core/office/";return e(e.s=12)})([function(b,e,d){d.d(e,"b",function(){return c});d.d(e,"a",function(){return k});var a=d(2),
c=function(b,c){Object(a.a)("disableLogs")||(c?console.warn(b+": "+c):console.warn(b))},k=function(a,b){}},function(b,e,d){d.d(e,"a",function(){return w});d.d(e,"b",function(){return K});d.d(e,"c",function(){return H});var a=d(6),c=d(0),k=d(11),r=d(3),u="undefined"===typeof window?self:window,f=u.importScripts,p=function(a){if("string"===typeof a){for(var b=new Uint8Array(a.length),c=a.length,m=0;m<c;m++)b[m]=a.charCodeAt(m);return b}return a},y=function(a){if("string"!==typeof a){for(var b="",c=
0,m=a.length,e;c<m;)e=a.subarray(c,c+1024),c+=1024,b+=String.fromCharCode.apply(null,e);return b}return a},t=!1,g=function(a,b){t||(f(u.basePath+"decode.min.js"),t=!0);a=self.BrotliDecode(p(a));return b?a:y(a)},n=function(b,c){return Object(a.a)(void 0,void 0,Promise,function(){var m;return Object(a.b)(this,function(a){switch(a.label){case 0:return t?[3,2]:[4,Object(r.b)(self.CoreControls.getWorkerPath()+"external/decode.min.js","Failed to download decode.min.js",window)];case 1:a.sent(),t=!0,a.label=
2;case 2:return m=self.BrotliDecode(p(b)),[2,c?m:y(m)]}})})};(function(){function a(){this.remainingDataArrays=[]}a.prototype.processRaw=function(a){return a};a.prototype.processBrotli=function(a){this.remainingDataArrays.push(a);return null};a.prototype.GetNextChunk=function(a){this.decodeFunction||(this.decodeFunction=0===a[0]&&97===a[1]&&115===a[2]&&109===a[3]?this.processRaw:this.processBrotli);return this.decodeFunction(a)};a.prototype.End=function(){if(this.remainingDataArrays.length){for(var a=
this.arrays,b=0,c=0;c<a.length;++c)b+=a[c].length;b=new Uint8Array(b);var m=0;for(c=0;c<a.length;++c){var e=a[c];b.set(e,m);m+=e.length}return g(b,!0)}return null};return a})();var v=!1,x=function(a,b){v||(f(u.basePath+"rawinflate.js",u.basePath+"pako_inflate.min.js"),v=!0);var c=10;if("string"===typeof a){if(a.charCodeAt(3)&8){for(;0!==a.charCodeAt(c);++c);++c}}else if(a[3]&8){for(;0!==a[c];++c);++c}if(b)return a=p(a),a=a.subarray(c,a.length-8),u.pako.inflate(a,{windowBits:-15});a=y(a);a=a.substring(c,
a.length-8);return k.a.inflate(a)},m=function(a,b){return b?a:y(a)},l=function(a){var b=!a.shouldOutputArray,m=new XMLHttpRequest;m.open("GET",a.url,a.isAsync);var e=b&&m.overrideMimeType;m.responseType=e?"text":"arraybuffer";e&&m.overrideMimeType("text/plain; charset=x-user-defined");m.send();var d=function(){var d=Date.now();var B=e?m.responseText:new Uint8Array(m.response);Object(c.a)("worker","Result length is "+B.length);B.length<a.compressedMaximum?(B=a.decompressFunction(B,a.shouldOutputArray),
Object(c.b)("There may be some degradation of performance. Your server has not been configured to serve .gz. and .br. files with the expected Content-Encoding. See http://www.pdftron.com/kb_content_encoding for instructions on how to resolve this."),f&&Object(c.a)("worker","Decompressed length is "+B.length)):b&&(B=y(B));f&&Object(c.a)("worker",a.url+" Decompression took "+(Date.now()-d));return B};if(a.isAsync)var h=new Promise(function(b,c){m.onload=function(){200===this.status||0===this.status?
b(d()):c("Download Failed "+a.url)};m.onerror=function(){c("Network error occurred "+a.url)}});else{if(200===m.status||0===m.status)return d();throw Error("Failed to load "+a.url);}return h},w=function(a){var b=a.lastIndexOf("/");-1===b&&(b=0);var c=a.slice(b).replace(".",".br.");f||(c.endsWith(".js.mem")?c=c.replace(".js.mem",".mem"):c.endsWith(".js")&&(c=c.concat(".mem")));return a.slice(0,b)+c},z=function(a,b){var c=a.lastIndexOf("/");-1===c&&(c=0);var m=a.slice(c).replace(".",".gz.");b.url=a.slice(0,
c)+m;b.decompressFunction=x;return l(b)},D=function(a,b){b.url=w(a);b.decompressFunction=f?g:n;return l(b)},h=function(a,b){a.endsWith(".js.mem")?a=a.slice(0,-4):a.endsWith(".mem")&&(a=a.slice(0,-4)+".js.mem");b.url=a;b.decompressFunction=m;return l(b)},q=function(a,b,m,e){return a.catch(function(a){Object(c.b)(a);return e(b,m)})},E=function(a,b,m){var e;if(m.isAsync){var d=b[0](a,m);for(e=1;e<b.length;++e)d=q(d,a,m,b[e]);return d}for(e=0;e<b.length;++e)try{return b[e](a,m)}catch(N){Object(c.b)(N.message)}throw Error("");
},H=function(a,b,c,m){return E(a,[z,D,h],{compressedMaximum:b,isAsync:c,shouldOutputArray:m})},K=function(a,b,c,m){return E(a,[D,z,h],{compressedMaximum:b,isAsync:c,shouldOutputArray:m})}},function(b,e,d){d.d(e,"a",function(){return k});d.d(e,"b",function(){return r});var a={},c={flattenedResources:!1,CANVAS_CACHE_SIZE:void 0,maxPagesBefore:void 0,maxPagesAhead:void 0,disableLogs:!1,_trnDebugMode:!1,_logFiltersEnabled:null},k=function(a){return c[a]},r=function(b,e){var d;c[b]=e;null===(d=a[b])||
void 0===d?void 0:d.forEach(function(a){a(e)})}},function(b,e,d){function a(a,b,c){function e(p){f=f||Date.now();return p?(Object(k.a)("load","Try instantiateStreaming"),fetch(Object(r.a)(a)).then(function(a){return WebAssembly.instantiateStreaming(a,b)}).catch(function(b){Object(k.a)("load","instantiateStreaming Failed "+a+" message "+b.message);return e(!1)})):Object(r.b)(a,c,!0,!0).then(function(a){d=Date.now();Object(k.a)("load","Request took "+(d-f)+" ms");return WebAssembly.instantiate(a,b)})}
var d,f;return e(!!WebAssembly.instantiateStreaming).then(function(a){Object(k.a)("load","WASM compilation took "+(Date.now()-(d||f))+" ms");return a})}function c(a,b,c){return new Promise(function(e){if(!a)return e();var d=c.document.createElement("script");d.type="text/javascript";d.onload=function(){e()};d.onerror=function(){b&&Object(k.b)(b);e()};d.src=a;c.document.getElementsByTagName("head")[0].appendChild(d)})}d.d(e,"a",function(){return a});d.d(e,"b",function(){return c});var k=d(0),r=d(1)},
function(b,e,d){d.d(e,"c",function(){return r});d.d(e,"b",function(){return u});d.d(e,"a",function(){return f});var a="undefined"===typeof window?self:window;b=function(){var a=navigator.userAgent.toLowerCase();return(a=/(msie) ([\w.]+)/.exec(a)||/(trident)(?:.*? rv:([\w.]+)|)/.exec(a))?parseInt(a[2],10):a}();(function(){var b=a.navigator.userAgent.match(/Chrome\/(.*?) /);return b?parseInt(b[1],10):b})();(function(){var b=a.navigator.userAgent.match(/OPR/),c=a.navigator.userAgent.match(/Maxthon/),
e=a.navigator.userAgent.match(/Edge/);return a.navigator.userAgent.match(/Chrome\/(.*?) /)&&!b&&!c&&!e})();navigator.userAgent.match(/Edge/i);e=/iPad|iPhone|iPod/.test(a.navigator.platform)||"MacIntel"===navigator.platform&&1<navigator.maxTouchPoints;(function(){var b=a.navigator.userAgent.match(/.*\/([0-9\.]+)\s(Safari|Mobile).*/i);return b?parseFloat(b[1]):b})();var c=/^((?!chrome|android).)*safari/i.test(a.navigator.userAgent)||/^((?!chrome|android).)*$/.test(a.navigator.userAgent)&&e;a.navigator.userAgent.match(/Firefox/);
b||/Android|webOS|Touch|IEMobile|Silk/i.test(navigator.userAgent);navigator.userAgent.match(/(iPad|iPhone|iPod)/i);a.navigator.userAgent.indexOf("Android");var k=/Mac OS X 10_13_6.*\(KHTML, like Gecko\)$/.test(a.navigator.userAgent),r=function(){return c||k},u=!(!self.WebAssembly||!self.WebAssembly.validate),f=-1<a.navigator.userAgent.indexOf("Edge/16")||-1<a.navigator.userAgent.indexOf("MSAppHost")},function(b,e){e=function(){return this}();try{e=e||(new Function("return this"))()}catch(d){"object"===
typeof window&&(e=window)}b.exports=e},function(b,e,d){function a(a,b,c,e){function d(a){return a instanceof c?a:new c(function(b){b(a)})}return new (c||(c=Promise))(function(c,f){function k(a){try{v(e.next(a))}catch(m){f(m)}}function p(a){try{v(e["throw"](a))}catch(m){f(m)}}function v(a){a.done?c(a.value):d(a.value).then(k,p)}v((e=e.apply(a,b||[])).next())})}function c(a,b){function c(a){return function(b){return e([a,b])}}function e(c){if(k)throw new TypeError("Generator is already executing.");
for(;d;)try{if(k=1,t&&(g=c[0]&2?t["return"]:c[0]?t["throw"]||((g=t["return"])&&g.call(t),0):t.next)&&!(g=g.call(t,c[1])).done)return g;if(t=0,g)c=[c[0]&2,g.value];switch(c[0]){case 0:case 1:g=c;break;case 4:return d.label++,{value:c[1],done:!1};case 5:d.label++;t=c[1];c=[0];continue;case 7:c=d.ops.pop();d.trys.pop();continue;default:if(!(g=d.trys,g=0<g.length&&g[g.length-1])&&(6===c[0]||2===c[0])){d=0;continue}if(3===c[0]&&(!g||c[1]>g[0]&&c[1]<g[3]))d.label=c[1];else if(6===c[0]&&d.label<g[1])d.label=
g[1],g=c;else if(g&&d.label<g[2])d.label=g[2],d.ops.push(c);else{g[2]&&d.ops.pop();d.trys.pop();continue}}c=b.call(a,d)}catch(x){c=[6,x],t=0}finally{k=g=0}if(c[0]&5)throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}var d={label:0,sent:function(){if(g[0]&1)throw g[1];return g[1]},trys:[],ops:[]},k,t,g,n;return n={next:c(0),"throw":c(1),"return":c(2)},"function"===typeof Symbol&&(n[Symbol.iterator]=function(){return this}),n}d.d(e,"a",function(){return a});d.d(e,"b",function(){return c})},function(b,
e,d){e.a=function(){ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var c=new ArrayBuffer(b-a),e=new Uint8Array(c);a=new Uint8Array(this,a,b-a);e.set(a);return c})}},function(b,e,d){d.d(e,"a",function(){return a});d(9);var a=
function(a,b){return function(){}}},function(b,e,d){e.a=function(a){var b={};decodeURIComponent(a.slice(1)).split("&").forEach(function(a){a=a.split("=",2);b[a[0]]=a[1]});return b}},function(b,e,d){d.d(e,"a",function(){return u});var a=d(1),c=d(3),k=d(4),r=function(){function a(a){var b=this;this.promise=a.then(function(a){b.response=a;b.status=200})}a.prototype.addEventListener=function(a,b){this.promise.then(b)};return a}(),u=function(b,e,d){if(!k.b||k.a||Object(k.c)()||d){d=Object(a.b)((self.Module.asmjsPrefix?
self.Module.asmjsPrefix:"")+b+".js.mem",e[".js.mem"],!1);var f=Object(a.c)((self.Module.memoryInitializerPrefixURL?self.Module.memoryInitializerPrefixURL:"")+b+".mem",e[".mem"],!0,!0);self.Module.memoryInitializerRequest=new r(f)}else self.Module.instantiateWasm=function(a,d){return Object(c.a)(b+"Wasm.wasm",a,e["Wasm.wasm"]).then(function(a){d(a.instance)})},d=Object(a.b)(b+"Wasm.js.mem",e["Wasm.js.mem"],!1,!1);d=new Blob([d],{type:"application/javascript"});importScripts(URL.createObjectURL(d))}},
function(b,e,d){var a=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],c=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],k=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],r=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],u=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],f=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],p=function(){this.list=
this.next=null},y=function(){this.n=this.b=this.e=0;this.t=null},t=function(a,b,c,m,e,d){this.BMAX=16;this.N_MAX=288;this.status=0;this.root=null;this.m=0;var f=Array(this.BMAX+1),l,h,q,k=Array(this.BMAX+1),u,g=new y,w=Array(this.BMAX);var n=Array(this.N_MAX);var v=Array(this.BMAX+1),B,F;var x=this.root=null;for(h=0;h<f.length;h++)f[h]=0;for(h=0;h<k.length;h++)k[h]=0;for(h=0;h<w.length;h++)w[h]=null;for(h=0;h<n.length;h++)n[h]=0;for(h=0;h<v.length;h++)v[h]=0;var t=256<b?a[256]:this.BMAX;var A=a;var r=
0;h=b;do f[A[r]]++,r++;while(0<--h);if(f[0]==b)this.root=null,this.status=this.m=0;else{for(q=1;q<=this.BMAX&&0==f[q];q++);var G=q;d<q&&(d=q);for(h=this.BMAX;0!=h&&0==f[h];h--);var J=h;d>h&&(d=h);for(B=1<<q;q<h;q++,B<<=1)if(0>(B-=f[q])){this.status=2;this.m=d;return}if(0>(B-=f[h]))this.status=2,this.m=d;else{f[h]+=B;v[1]=q=0;A=f;r=1;for(u=2;0<--h;)v[u++]=q+=A[r++];A=a;h=r=0;do 0!=(q=A[r++])&&(n[v[q]++]=h);while(++h<b);b=v[J];v[0]=h=0;A=n;r=0;n=-1;var C=k[0]=0;u=null;for(F=0;G<=J;G++)for(a=f[G];0<
a--;){for(;G>C+k[1+n];){C+=k[1+n];n++;F=(F=J-C)>d?d:F;if((l=1<<(q=G-C))>a+1)for(l-=a+1,u=G;++q<F&&!((l<<=1)<=f[++u]);)l-=f[u];C+q>t&&C<t&&(q=t-C);F=1<<q;k[1+n]=q;u=Array(F);for(l=0;l<F;l++)u[l]=new y;x=null==x?this.root=new p:x.next=new p;x.next=null;x.list=u;w[n]=u;0<n&&(v[n]=h,g.b=k[n],g.e=16+q,g.t=u,q=(h&(1<<C)-1)>>C-k[n],w[n-1][q].e=g.e,w[n-1][q].b=g.b,w[n-1][q].n=g.n,w[n-1][q].t=g.t)}g.b=G-C;r>=b?g.e=99:A[r]<c?(g.e=256>A[r]?16:15,g.n=A[r++]):(g.e=e[A[r]-c],g.n=m[A[r++]-c]);l=1<<G-C;for(q=h>>
C;q<F;q+=l)u[q].e=g.e,u[q].b=g.b,u[q].n=g.n,u[q].t=g.t;for(q=1<<G-1;0!=(h&q);q>>=1)h^=q;for(h^=q;(h&(1<<C)-1)!=v[n];)C-=k[n],n--}this.m=k[1];this.status=0!=B&&1!=J?1:0}}},g={Stream:function(a){this.zip_inflate_start();this.zip_inflate_data=a;this.zip_inflate_pos=0}};g.Stream.prototype={getBytes:function(a){for(var b,c=Array(1024),e=[],d=0;d<a&&0<(b=this.zip_inflate_internal(c,0,c.length));)e[e.length]=String.fromCharCode.apply(null,c.slice(0,b)),d+=b;return d?(this.zip_inflate_data=this.zip_inflate_data.slice(this.zip_inflate_pos),
this.zip_inflate_pos=0,e.join("")):""},zip_GET_BYTE:function(){return this.zip_inflate_data.length==this.zip_inflate_pos?-1:this.zip_inflate_data.charCodeAt(this.zip_inflate_pos++)&255},zip_NEEDBITS:function(a){for(;this.zip_bit_len<a;)this.zip_bit_buf|=this.zip_GET_BYTE()<<this.zip_bit_len,this.zip_bit_len+=8},zip_GETBITS:function(b){return this.zip_bit_buf&a[b]},zip_DUMPBITS:function(a){this.zip_bit_buf>>=a;this.zip_bit_len-=a},zip_inflate_codes:function(a,b,c){var e,d;if(0==c)return 0;for(d=0;;){this.zip_NEEDBITS(this.zip_bl);
var f=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];for(e=f.e;16<e;){if(99==e)return-1;this.zip_DUMPBITS(f.b);e-=16;this.zip_NEEDBITS(e);f=f.t[this.zip_GETBITS(e)];e=f.e}this.zip_DUMPBITS(f.b);if(16==e)this.zip_wp&=32767,a[b+d++]=this.zip_slide[this.zip_wp++]=f.n;else{if(15==e)break;this.zip_NEEDBITS(e);this.zip_copy_leng=f.n+this.zip_GETBITS(e);this.zip_DUMPBITS(e);this.zip_NEEDBITS(this.zip_bd);f=this.zip_td.list[this.zip_GETBITS(this.zip_bd)];for(e=f.e;16<e;){if(99==e)return-1;this.zip_DUMPBITS(f.b);
e-=16;this.zip_NEEDBITS(e);f=f.t[this.zip_GETBITS(e)];e=f.e}this.zip_DUMPBITS(f.b);this.zip_NEEDBITS(e);this.zip_copy_dist=this.zip_wp-f.n-this.zip_GETBITS(e);for(this.zip_DUMPBITS(e);0<this.zip_copy_leng&&d<c;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=32767,a[b+d++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++]}if(d==c)return c}this.zip_method=-1;return d},zip_inflate_stored:function(a,b,c){var e=this.zip_bit_len&7;this.zip_DUMPBITS(e);this.zip_NEEDBITS(16);
e=this.zip_GETBITS(16);this.zip_DUMPBITS(16);this.zip_NEEDBITS(16);if(e!=(~this.zip_bit_buf&65535))return-1;this.zip_DUMPBITS(16);this.zip_copy_leng=e;for(e=0;0<this.zip_copy_leng&&e<c;)this.zip_copy_leng--,this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+e++]=this.zip_slide[this.zip_wp++]=this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1);return e},zip_inflate_fixed:function(a,b,e){if(null==this.zip_fixed_tl){var d,f=Array(288);for(d=0;144>d;d++)f[d]=8;for(;256>d;d++)f[d]=
9;for(;280>d;d++)f[d]=7;for(;288>d;d++)f[d]=8;this.zip_fixed_bl=7;d=new t(f,288,257,c,k,this.zip_fixed_bl);if(0!=d.status)return alert("HufBuild error: ".concat(d.status)),-1;this.zip_fixed_tl=d.root;this.zip_fixed_bl=d.m;for(d=0;30>d;d++)f[d]=5;this.zip_fixed_bd=5;d=new t(f,30,0,r,u,this.zip_fixed_bd);if(1<d.status)return this.zip_fixed_tl=null,alert("HufBuild error: ".concat(d.status)),-1;this.zip_fixed_td=d.root;this.zip_fixed_bd=d.m}this.zip_tl=this.zip_fixed_tl;this.zip_td=this.zip_fixed_td;
this.zip_bl=this.zip_fixed_bl;this.zip_bd=this.zip_fixed_bd;return this.zip_inflate_codes(a,b,e)},zip_inflate_dynamic:function(a,b,e){var d,l,g,n=Array(316);for(d=0;d<n.length;d++)n[d]=0;this.zip_NEEDBITS(5);var p=257+this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(5);var h=1+this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(4);d=4+this.zip_GETBITS(4);this.zip_DUMPBITS(4);if(286<p||30<h)return-1;for(l=0;l<d;l++)this.zip_NEEDBITS(3),n[f[l]]=this.zip_GETBITS(3),this.zip_DUMPBITS(3);
for(;19>l;l++)n[f[l]]=0;this.zip_bl=7;l=new t(n,19,19,null,null,this.zip_bl);if(0!=l.status)return-1;this.zip_tl=l.root;this.zip_bl=l.m;var q=p+h;for(d=g=0;d<q;){this.zip_NEEDBITS(this.zip_bl);var E=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];l=E.b;this.zip_DUMPBITS(l);l=E.n;if(16>l)n[d++]=g=l;else if(16==l){this.zip_NEEDBITS(2);l=3+this.zip_GETBITS(2);this.zip_DUMPBITS(2);if(d+l>q)return-1;for(;0<l--;)n[d++]=g}else{17==l?(this.zip_NEEDBITS(3),l=3+this.zip_GETBITS(3),this.zip_DUMPBITS(3)):(this.zip_NEEDBITS(7),
l=11+this.zip_GETBITS(7),this.zip_DUMPBITS(7));if(d+l>q)return-1;for(;0<l--;)n[d++]=0;g=0}}this.zip_bl=9;l=new t(n,p,257,c,k,this.zip_bl);0==this.zip_bl&&(l.status=1);if(0!=l.status)return-1;this.zip_tl=l.root;this.zip_bl=l.m;for(d=0;d<h;d++)n[d]=n[d+p];this.zip_bd=6;l=new t(n,h,0,r,u,this.zip_bd);this.zip_td=l.root;this.zip_bd=l.m;return 0==this.zip_bd&&257<p||0!=l.status?-1:this.zip_inflate_codes(a,b,e)},zip_inflate_start:function(){null==this.zip_slide&&(this.zip_slide=Array(65536));this.zip_bit_len=
this.zip_bit_buf=this.zip_wp=0;this.zip_method=-1;this.zip_eof=!1;this.zip_copy_leng=this.zip_copy_dist=0;this.zip_fixed_tl=this.zip_tl=null},zip_inflate_internal:function(a,b,c){var d;for(d=0;d<c&&(!this.zip_eof||-1!=this.zip_method);){if(0<this.zip_copy_leng){if(0!=this.zip_method)for(;0<this.zip_copy_leng&&d<c;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=32767,a[b+d++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++];else{for(;0<this.zip_copy_leng&&d<c;)this.zip_copy_leng--,
this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+d++]=this.zip_slide[this.zip_wp++]=this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1)}if(d==c)break}if(-1==this.zip_method){if(this.zip_eof)break;this.zip_NEEDBITS(1);0!=this.zip_GETBITS(1)&&(this.zip_eof=!0);this.zip_DUMPBITS(1);this.zip_NEEDBITS(2);this.zip_method=this.zip_GETBITS(2);this.zip_DUMPBITS(2);this.zip_tl=null;this.zip_copy_leng=0}switch(this.zip_method){case 0:var e=this.zip_inflate_stored(a,b+d,c-d);break;
case 1:e=null!=this.zip_tl?this.zip_inflate_codes(a,b+d,c-d):this.zip_inflate_fixed(a,b+d,c-d);break;case 2:e=null!=this.zip_tl?this.zip_inflate_codes(a,b+d,c-d):this.zip_inflate_dynamic(a,b+d,c-d);break;default:e=-1}if(-1==e)return this.zip_eof?0:-1;d+=e}return d}};g.inflate=function(a){return(new g.Stream(a)).getBytes(4E9)};e.a=g},function(b,e,d){b.exports=d(13)},function(b,e,d){d.r(e);d(14);d(19);b=d(7);d(20);Object(b.a)()},function(b,e,d){(function(a,b){function c(a){"@babel/helpers - typeof";
c="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return c(a)}(function(a){function e(){for(var a=0;a<I.length;a++)I[a][0](I[a][1]);I=[];L=!1}function f(a,b){I.push([a,b]);L||(L=!0,M(e,0))}function k(a,b){function c(a){g(b,a)}function d(a){v(b,a)}try{a(c,d)}catch(A){d(A)}}function r(a){var b=a.owner,c=b.state_;b=b.data_;var d=a[c];a=a.then;if("function"===
typeof d){c=E;try{b=d(b)}catch(A){v(a,A)}}t(a,b)||(c===E&&g(a,b),c===H&&v(a,b))}function t(a,b){var d;try{if(a===b)throw new TypeError("A promises callback cannot return that same promise.");if(b&&("function"===typeof b||"object"===c(b))){var e=b.then;if("function"===typeof e)return e.call(b,function(c){d||(d=!0,b!==c?g(a,c):n(a,c))},function(b){d||(d=!0,v(a,b))}),!0}}catch(A){return d||v(a,A),!0}return!1}function g(a,b){a!==b&&t(a,b)||n(a,b)}function n(a,b){a.state_===h&&(a.state_=q,a.data_=b,f(m,
a))}function v(a,b){a.state_===h&&(a.state_=q,a.data_=b,f(l,a))}function x(a){var b=a.then_;a.then_=void 0;for(a=0;a<b.length;a++)r(b[a])}function m(a){a.state_=E;x(a)}function l(a){a.state_=H;x(a)}function w(a){if("function"!==typeof a)throw new TypeError("Promise constructor takes a function argument");if(!1===this instanceof w)throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");this.then_=[];k(a,this)}a.createPromiseCapability=
function(){var a={},b=new w(function(b,c){a.resolve=b;a.reject=c});a.promise=b;return a};var z=a.Promise,D=z&&"resolve"in z&&"reject"in z&&"all"in z&&"race"in z&&function(){var a;new z(function(b){a=b});return"function"===typeof a}();"undefined"!==typeof exports&&exports?(exports.Promise=D?z:w,exports.Polyfill=w):"function"===typeof define&&d(18)?define(function(){return D?z:w}):D||(a.Promise=w);var h="pending",q="sealed",E="fulfilled",H="rejected",K=function(){},M="undefined"!==typeof b?b:setTimeout,
I=[],L;w.prototype={constructor:w,state_:h,then_:null,data_:void 0,then:function(a,b){a={owner:this,then:new this.constructor(K),fulfilled:a,rejected:b};this.state_===E||this.state_===H?f(r,a):this.then_.push(a);return a.then},"catch":function(a){return this.then(null,a)}};w.all=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.all().");return new this(function(b,c){function d(a){f++;return function(c){e[a]=c;--f||b(e)}}for(var e=
[],f=0,h=0,k;h<a.length;h++)(k=a[h])&&"function"===typeof k.then?k.then(d(h),c):e[h]=k;f||b(e)})};w.race=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.race().");return new this(function(b,c){for(var d=0,e;d<a.length;d++)(e=a[d])&&"function"===typeof e.then?e.then(b,c):b(e)})};w.resolve=function(a){return a&&"object"===c(a)&&a.constructor===this?a:new this(function(b){b(a)})};w.reject=function(a){return new this(function(b,
c){c(a)})}})("undefined"!==typeof window?window:"undefined"!==typeof a?a:"undefined"!==typeof self?self:void 0)}).call(this,d(5),d(15).setImmediate)},function(b,e,d){(function(a){function b(a,b){this._id=a;this._clearFn=b}var k="undefined"!==typeof a&&a||"undefined"!==typeof self&&self||window,r=Function.prototype.apply;e.setTimeout=function(){return new b(r.call(setTimeout,k,arguments),clearTimeout)};e.setInterval=function(){return new b(r.call(setInterval,k,arguments),clearInterval)};e.clearTimeout=
e.clearInterval=function(a){a&&a.close()};b.prototype.unref=b.prototype.ref=function(){};b.prototype.close=function(){this._clearFn.call(k,this._id)};e.enroll=function(a,b){clearTimeout(a._idleTimeoutId);a._idleTimeout=b};e.unenroll=function(a){clearTimeout(a._idleTimeoutId);a._idleTimeout=-1};e._unrefActive=e.active=function(a){clearTimeout(a._idleTimeoutId);var b=a._idleTimeout;0<=b&&(a._idleTimeoutId=setTimeout(function(){a._onTimeout&&a._onTimeout()},b))};d(16);e.setImmediate="undefined"!==typeof self&&
self.setImmediate||"undefined"!==typeof a&&a.setImmediate||this&&this.setImmediate;e.clearImmediate="undefined"!==typeof self&&self.clearImmediate||"undefined"!==typeof a&&a.clearImmediate||this&&this.clearImmediate}).call(this,d(5))},function(b,e,d){(function(a,b){(function(a,c){function d(a){delete m[a]}function e(a){if(l)setTimeout(e,0,a);else{var b=m[a];if(b){l=!0;try{var f=b.callback,h=b.args;switch(h.length){case 0:f();break;case 1:f(h[0]);break;case 2:f(h[0],h[1]);break;case 3:f(h[0],h[1],
h[2]);break;default:f.apply(c,h)}}finally{d(a),l=!1}}}}function k(){z=function(a){b.nextTick(function(){e(a)})}}function r(){if(a.postMessage&&!a.importScripts){var b=!0,c=a.onmessage;a.onmessage=function(){b=!1};a.postMessage("","*");a.onmessage=c;return b}}function t(){var b="setImmediate$"+Math.random()+"$",c=function(c){c.source===a&&"string"===typeof c.data&&0===c.data.indexOf(b)&&e(+c.data.slice(b.length))};a.addEventListener?a.addEventListener("message",c,!1):a.attachEvent("onmessage",c);z=
function(c){a.postMessage(b+c,"*")}}function g(){var a=new MessageChannel;a.port1.onmessage=function(a){e(a.data)};z=function(b){a.port2.postMessage(b)}}function n(){var a=w.documentElement;z=function(b){var c=w.createElement("script");c.onreadystatechange=function(){e(b);c.onreadystatechange=null;a.removeChild(c);c=null};a.appendChild(c)}}function v(){z=function(a){setTimeout(e,0,a)}}if(!a.setImmediate){var x=1,m={},l=!1,w=a.document,z,D=Object.getPrototypeOf&&Object.getPrototypeOf(a);D=D&&D.setTimeout?
D:a;"[object process]"==={}.toString.call(a.process)?k():r()?t():a.MessageChannel?g():w&&"onreadystatechange"in w.createElement("script")?n():v();D.setImmediate=function(a){"function"!==typeof a&&(a=new Function(""+a));for(var b=Array(arguments.length-1),c=0;c<b.length;c++)b[c]=arguments[c+1];m[x]={callback:a,args:b};z(x);return x++};D.clearImmediate=d}})("undefined"===typeof self?"undefined"===typeof a?this:a:self)}).call(this,d(5),d(17))},function(b,e){function d(){throw Error("setTimeout has not been defined");
}function a(){throw Error("clearTimeout has not been defined");}function c(a){if(y===setTimeout)return setTimeout(a,0);if((y===d||!y)&&setTimeout)return y=setTimeout,setTimeout(a,0);try{return y(a,0)}catch(l){try{return y.call(null,a,0)}catch(w){return y.call(this,a,0)}}}function k(b){if(t===clearTimeout)return clearTimeout(b);if((t===a||!t)&&clearTimeout)return t=clearTimeout,clearTimeout(b);try{return t(b)}catch(l){try{return t.call(null,b)}catch(w){return t.call(this,b)}}}function r(){n&&v&&(n=
!1,v.length?g=v.concat(g):x=-1,g.length&&u())}function u(){if(!n){var a=c(r);n=!0;for(var b=g.length;b;){v=g;for(g=[];++x<b;)v&&v[x].run();x=-1;b=g.length}v=null;n=!1;k(a)}}function f(a,b){this.fun=a;this.array=b}function p(){}b=b.exports={};try{var y="function"===typeof setTimeout?setTimeout:d}catch(m){y=d}try{var t="function"===typeof clearTimeout?clearTimeout:a}catch(m){t=a}var g=[],n=!1,v,x=-1;b.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var d=1;d<arguments.length;d++)b[d-
1]=arguments[d];g.push(new f(a,b));1!==g.length||n||c(u)};f.prototype.run=function(){this.fun.apply(null,this.array)};b.title="browser";b.browser=!0;b.env={};b.argv=[];b.version="";b.versions={};b.on=p;b.addListener=p;b.once=p;b.off=p;b.removeListener=p;b.removeAllListeners=p;b.emit=p;b.prependListener=p;b.prependOnceListener=p;b.listeners=function(a){return[]};b.binding=function(a){throw Error("process.binding is not supported");};b.cwd=function(){return"/"};b.chdir=function(a){throw Error("process.chdir is not supported");
};b.umask=function(){return 0}},function(b,e){b.exports={}},function(b,e,d){(function(a){"undefined"===typeof a.crypto&&(a.crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()}})})("undefined"===typeof window?self:window)},function(b,e,d){function a(b){"@babel/helpers - typeof";a="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":
typeof a};return a(b)}var c=d(8),k=d(10),r=null;(function(b){function d(){t=function(){}}function e(b){var c=[];return{resource_array:c,msg:JSON.stringify(b.data,function(b,d){if("object"===a(d)&&(b=null,d instanceof Uint8Array?b=d:d instanceof ArrayBuffer&&(b=new Uint8Array(d)),b)){d=n(b.length);var e=v(d);e&&(new Uint8Array(Module.HEAPU8.buffer,e,b.length)).set(b);c.push(d);return{__trn_res_id:d}}return d})}}function u(a){a=e(a);g(a.msg)}var t,g,n,v;b.basePath="../";var x=b.officeWorkerPath||"";
b.workerBasePath&&(b.basePath=b.workerBasePath);var m=function(a){var b={};decodeURIComponent(a.slice(1)).split("&").forEach(function(a){a=a.split("=",2);b[a[0]]=a[1]});return b}(b.location.search);b.basePath=m.externalPath?m.externalPath:b.basePath+"external/";importScripts("".concat(b.basePath,"Promise.js"));var l=[];onmessage=function(a){l||(l=[]);l.push(a)};b.ContinueFunc=function(a){t("ContinueFunc called");setTimeout(function(){onmessage({data:{action:"continue"}})},a)};if(m.pdfWorkerPath)var w=
m.pdfWorkerPath;if(m.officeAsmPath)var z=m.officeAsmPath;b.Module={memoryInitializerPrefixURL:w,asmjsPrefix:z,onRuntimeInitialized:function(){t||d();var a=Date.now()-r;Object(c.a)("load","time duration from start to ready: ".concat(JSON.stringify(a)));g=function(a){if(null!==a&&void 0!==a&&0!==a){var b=(a.length<<2)+1,c=Module._malloc(b);0<Module.stringToUTF8(a,c,b)&&Module._TRN_OnMessage(c)}};n=function(a){return Module._TRN_CreateBufferResource(a)};v=function(a){return Module._TRN_GetResourcePointer(a)};
t("OnReady called");onmessage=u;Module._TRN_InitWorker();for(a=0;a<l.length;++a)onmessage(l[a]);l=null},fetchSelf:function(){r=Date.now();Object(k.a)("".concat(x,"WebOfficeWorker"),{"Wasm.wasm":5E6,"Wasm.js.mem":1E5,".js.mem":5E6,".mem":3E6},!!navigator.userAgent.match(/Edge/i))},noExitRuntime:!0};b.Module.fetchSelf()})("undefined"===typeof window?self:window)}]);}).call(this || window)
