/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[5],{338:function(ha,da,f){function ba(e,f,h){f.endsWith("/")||(f+="/");h=h||{};var n=h.disableWebsockets||!1;this.AM=h.singleServerMode||!1;f.endsWith("blackbox/")||(f+="blackbox/");this.yl=h.uploadData||null;this.Ys=h.uriData||null;this.NG=h.cacheKey||null;this.Of=Object(w.a)(f,null,n);this.Ge=f;this.cA=e;this.Xe=null;this.Gj=ea();this.bm=ea();this.Yu=!1;this.Lf=this.Md=this.Zd=this.Ee=null;this.ef=[];this.Cv=[];this.cache={};this.timeStamp=
0;this.zf=[];this.Ag=[];this.rA=null;this.Wz=!1;this.LC=this.id=null;this.KB=this.zJ=fa;this.lx=0;this.hB=!1;this.oY=1;this.Dw={};this.aw=null;this.tp(!0)}function ea(){var e={promise:null,resolve:null,reject:null,state:0,result:null,request:null,Jm:function(){return 1===(e.state&1)},xX:function(){return 2===(e.state&2)},kh:function(){return!e.xX()&&!e.Jm()},kX:function(){return 4===(e.state&4)},WL:function(){e.state|=4}};e.promise=new Promise(function(f,h){e.resolve=function(){if(0===e.state||4===
e.state)e.state=1,e.result=arguments[0],f.apply(null,arguments)};e.reject=function(){if(0===e.state||4===e.state)e.state=2,h.apply(null,arguments)}});return e}function fa(){return!1}function aa(e,f,h){if(!(f in n))return!0;f=n[f];for(var r=0;r<f.length;r++){var w=e;var x=f[r];var y=h;if(x.name in w){var aa="",ba=!1;w=w[x.name];switch(x.type){case "s":aa="String";ba=Object(z.isString)(w);break;case "a":aa="Array";ba=Object(z.isArray)(w);break;case "n":aa="Number";ba=Object(z.isNumber)(w)&&Object(z.isFinite)(w);
break;case "o":aa="Object",ba=Object(z.isObject)(w)&&!Object(z.isArray)(w)}ba||y.reject('Expected response field "'+x.name+'" to have type '+aa);x=ba}else y.reject('Response missing field "'+x.name+'"'),x=!1;if(!x)return!1}return!0}f.r(da);var z=f(0);f.n(z);var y=f(1);ha=f(39);var x=f(27),w=f(355),r=f(71);f=f(280);var n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",
type:"a"},{name:"size",type:"n"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}]};ba.prototype=Object(z.extend)(ba.prototype,{JS:function(){var e=this;return new Promise(function(f,h){var n=new XMLHttpRequest;n.open("GET",e.Ge+"ck");n.withCredentials=e.ym();n.onreadystatechange=function(){n.readyState===XMLHttpRequest.DONE&&(200===n.status?f():h())};
n.send()})},G_:function(e,f){this.zJ=e||fa;this.KB=f||fa},cH:function(){var e=this;this.bm=ea();this.Gj=ea();return this.Of.mA().then(function(){e.Yu=!1;e.id=null;e.Wz=!1;return e.JS()})},zC:function(){this.zJ();this.mw();this.Ee&&(this.Ee.kh()?this.Ye(this.Ee.request):this.Ee.Jm()&&this.KB(this.Ee.result.url,"pdf")&&(this.Ee=null,this.uL()));this.Lf&&this.Lf.kh()&&this.Ye(this.Lf.request);this.Zd&&this.Zd.kh()?this.Ye(this.Zd.request):this.Md&&this.Md.kh()&&this.nJ(this.Md.request);var e;for(e=0;e<
this.zf.length;e++)this.zf[e]&&this.zf[e]&&(this.zf[e].kh()?this.Ye(this.zf[e].request):this.zf[e].Jm()&&this.KB(this.zf[e].result.url,"image")&&(this.zf[e]=null,this.ix(e)));for(e=0;e<this.Ag.length;e++)this.Ag[e]&&this.Ag[e]&&this.Ag[e].kh()&&!this.Ag[e].kX()&&this.Ye(this.Ag[e].request);for(e=0;e<this.ef.length;e++)this.ef[e]&&this.ef[e].kh()&&this.Ye(this.ef[e].request)},mw:function(){var e=this;this.Yu||(this.timeStamp=Date.now(),this.Of.iD(function(f){e.AY(f)}).then(function(){clearInterval(e.nC);
e.nC=null},function(f){Object(y.e)("Blackbox connection failed:"+f);e.Yu=!1;if(!e.nC){var h=0;e.Wz=!0;e.LC=0;e.nC=setInterval(function(){50>h++&&e.zC()},5E3)}}),this.Yu=!0)},w1:function(){var e=this,f=createPromiseCapability();if(this.yl){var h=new FormData;h.append("file",this.yl.fileHandle,this.yl.fileHandle.name);var n=this.yl.loadCallback;var r="upload";var w=this.yl.extension}else if(this.Ys){h={uri:this.Ys.uri,H4:this.Ys.shareId};h=Object.keys(h).map(function(e){return e+"="+(h[e]?encodeURIComponent(h[e]):
"")}).join("&");var y="application/x-www-form-urlencoded; charset=UTF-8";n=this.Ys.loadCallback;r="url";w=this.Ys.extension}else return Promise.resolve();var z=new XMLHttpRequest;z.open("POST",Object(x.h)(e.Ge,"AuxUpload?ext="+w+"&type="+r+"&bcid="+this.Of.clientId));z.withCredentials=this.ym();y&&z.setRequestHeader("Content-Type",y);z.addEventListener("load",function(){if(z.readyState===z.DONE&&200===z.status){var h=JSON.parse(z.response);e.cA=h.uri;n(h);f.resolve(h)}});z.addEventListener("error",
function(){f.reject(z.statusText+" "+JSON.stringify(z))});this.yl&&null!=this.yl.onProgress&&(z.upload.onprogress=function(f){e.yl.onProgress(f)});z.send(h);return f.promise},X_:function(e){this.aw=e},nW:function(e){this.password&&this.Gj.Jm()?e(this.password):this.aw(e)},zZ:function(e){this.password=e||null;this.Gj.Jm()||(this.mw(),this.Ye({t:"pages"}));return this.Gj.promise},Gs:function(e){this.rA=e||null;this.Gj.Jm()||(this.mw(),this.Ye({t:"pages"}));return this.Gj.promise},eH:function(e){e=Object.assign(e,
{uri:encodeURIComponent(this.cA)});this.rA&&(e.ext=this.rA);this.Xe&&(e.c=this.Xe);this.password&&(e.pswd=this.password);this.NG&&(e.cacheKey=this.NG);return e},Ye:function(e){e=this.eH(e);this.Of.send(e)},bj:function(e){return e},AY:function(e){var f=this,h=e.data,n=e.err,w=e.t;if(n&&f.aw&&"This document could not be decrypted with the given password"===n)f.aw(function(e){f.zZ(e)});else switch(w){case "upload":n?f.z1.reject(n):f.z1.resolve("Success");break;case "pages":n?f.Gj.reject(n):aa(h,w,f.Gj)&&
f.Gj.resolve(h);break;case "config":n?f.bm.reject(n):aa(h,w,f.bm)&&(h.id&&(f.id=h.id),h.serverVersion&&(f.M1=h.serverVersion,Object(y.f)("[WebViewer Server] server version: "+f.M1)),h.serverID?(f.lx=h.serverID===f.LC&&f.hB?f.lx+1:0,f.LC=h.serverID):f.lx=0,f.hB=!1,f.bm.resolve(h));break;case "health":n?f.bm.reject(n):aa(h,w,f.bm)&&(e=h.unhealthy,this.AM&&(e=h.isDead),!f.i3&&e&&1>=f.lx&&(f.hB=!0,f.cH().then(function(){f.zC()},function(){f.zC()})));break;case "pdf":h.url=f.Ge+"../"+encodeURI(h.url)+
"?bcid="+this.Of.clientId;n?f.Ee.reject(n):aa(h,w,f.Ee)&&f.Ee.resolve(h);break;case "docmod":h.url=f.Ge+"../"+encodeURI(h.url)+"?bcid="+this.Of.clientId;n?f.Dw[h.rID].reject(n):aa(h,w,f.Ee)&&f.Dw[h.rID].resolve(h);break;case "xod":if(n)this.Zd&&this.Zd.kh()&&this.Zd.reject(n),this.Md&&this.Md.kh()&&this.Md.reject(n);else if(h.notFound)h.noCreate||this.Zd&&this.Zd.kh()&&this.Zd.resolve(h),this.Md&&this.Md.kh()&&this.Md.resolve(h);else{h.url&&(h.url=f.Ge+"../"+encodeURI(h.url)+"?bcid="+this.Of.clientId);
if(!this.Md||this.Md.Jm())this.Md=ea(),this.Md.request={t:"xod",noCreate:!0};this.Zd||(this.Zd=ea(),this.Zd.request={t:"xod"});this.Md.resolve(h);this.Zd.resolve(h)}break;case "annots":if(n)f.Lf.reject(n);else if(aa(h,w,f.Lf)){f.Lf.WL();var x=new XMLHttpRequest;e=f.Ge+"../"+encodeURI(h.url);var z=h.hasAppearance?e+".xodapp?bcid="+this.Of.clientId:null;e+="?bcid="+this.Of.clientId;x.open("GET",e);x.responseType="text";x.withCredentials=this.ym();x.addEventListener("load",function(){x.readyState===
x.DONE&&200===x.status&&f.Lf.resolve({BD:x.response,zG:z})});x.addEventListener("error",function(){f.Lf.reject(x.statusText+" "+JSON.stringify(x))});x.send()}break;case "image":var ba=this.zf[h.p];n?ba.promise.reject(n):aa(h,w,ba)&&(ba.result=h,ba.result.url=f.Ge+"../"+encodeURI(ba.result.url)+"?bcid="+this.Of.clientId,ba.resolve(ba.result));break;case "tiles":ba=h.rID;e=this.ef[ba];this.ef[ba]=null;this.Cv.push(ba);if(n)e.reject(n);else if(aa(h,w,e)){for(n=0;n<h.tiles.length;n++)h.tiles[n]=f.Ge+
"../"+encodeURI(h.tiles[n])+"?bcid="+this.Of.clientId;e.resolve(h)}break;case "text":ba=this.Ag[h.p];if(n)ba.reject(n);else if(aa(h,w,ba)){ba.WL();var da=new XMLHttpRequest;da.open("GET",f.Ge+"../"+encodeURI(h.url)+"?bcid="+this.Of.clientId);da.withCredentials=this.ym();da.addEventListener("load",function(){da.readyState===da.DONE&&200===da.status&&(ba.result=JSON.parse(da.response),ba.resolve(ba.result))});da.addEventListener("error",function(e){ba.reject(da.statusText+" "+JSON.stringify(e))});da.send()}break;
case "progress":"loading"===h.t&&f.trigger(r.a.Events.DOCUMENT_LOADING_PROGRESS,[h.bytes,h.total])}},vI:function(){this.mw();return this.bm.promise},GU:function(){this.Lf||(this.Lf=ea(),this.Lf.request={t:"annots"},this.Ye(this.Lf.request));return this.Lf.promise},ix:function(e){this.zf[e]||(this.zf[e]=ea(),this.zf[e].request={t:"image",p:e},this.Ye(this.zf[e].request));return this.zf[e].promise},AZ:function(e){this.Ag[e]||(this.Ag[e]=ea(),this.Ag[e].request={t:"text",p:e},this.Ye(this.Ag[e].request));
return this.Ag[e].promise},BZ:function(e,f,h,n){var r=this.ef.length;this.Cv.length&&(r=this.Cv.pop());this.ef[r]=ea();this.ef[r].request={t:"tiles",p:e,z:f,r:h,size:n,rID:r};this.Ye(this.ef[r].request);return this.ef[r].promise},uL:function(){this.Ee||(this.Ee=ea(),this.Ee.request={t:"pdf"},this.Wz?this.Ee.resolve({url:this.cA}):this.Ye(this.Ee.request));return this.Ee.promise},MI:function(e){var f=this,h=new XMLHttpRequest,n=this.Ge+"aul?id="+this.id+"&bcid="+this.Of.clientId,r=new FormData,w={};
e.annots&&(w.annots="xfdf");e.watermark&&(w.watermark="png");e.redactions&&(w.redactions="redact");w={t:"docmod",reqID:this.oY++,parts:w};e.print&&(w.print=!0);var x=this.eH(w);r.append("msg",JSON.stringify(x));return Promise.all([e.annots,e.watermark,e.redactions].map(function(e){return Promise.resolve(e)})).then(function(e){var w=e[0],y=e[1],z=e[2];w&&r.append("annots",w);y&&r.append("watermark",e.watermark);z&&r.append("redactions",z);f.Dw[x.reqID]=ea();h.open("POST",n);h.withCredentials=f.ym;
h.send(r);return f.Dw[x.reqID].promise})},nJ:function(){this.Md||(this.Md=ea(),this.Md.request={t:"xod",noCreate:!0},this.Ye(this.Md.request));return this.Md.promise},CZ:function(){this.Zd||(this.Zd=ea(),this.Zd.request={t:"xod"},this.Ye(this.Zd.request));return this.Zd.promise},ml:function(){return!0},request:function(){},eL:function(){},abort:function(){for(var e=0;e<this.ef.length;e++)this.ef[e]&&(this.ef[e].resolve(null),this.ef[e]=null,this.Cv.push(e));this.close()},rx:function(e){this.Xe=this.Xe||
{};this.Xe.headers=e},G3:function(){return this.Xe?Object(z.omit)(this.Xe.headers,["Cookie","cookie"]):null},tp:function(e){this.Xe=this.Xe||{};this.Xe.internal=this.Xe.internal||{};this.Xe.internal.withCredentials=e},ym:function(){return this.Xe&&this.Xe.internal?this.Xe.internal.withCredentials:null},getFileData:function(){return Promise.reject()}});Object(ha.b)(ba);Object(f.a)(ba);Object(f.b)(ba);da["default"]=ba},355:function(ha,da,f){function ba(f){for(var z="",y=0;y<f;y++)z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*
Math.random()));return z}function ea(f,z,y){function x(f,e,r){function h(e){w().then(function(f){ca&&!da?setTimeout(function(){h(e)},1):f.send(JSON.stringify(e))})}function n(e,f,n){var w=window.createPromiseCapability(),ha=!1,ia=w;z=e;ba=f;aa=n;y=null;try{e=ea?fa+"/"+ea:fa+"/ws";e+="?bcid="+r;var ja=new WebSocket(e);ja.onopen=function(){w.resolve();ha=!0;w=null;ca=!1;x.resolve(ja);ba&&ba()};ja.onerror=function(e){ca=da=!0;w&&w.reject(e);y&&y.reject()};ja.onclose=function(){x=window.createPromiseCapability();
ca=!0;y||(y=window.createPromiseCapability());y.resolve();aa&&aa();z&&ha&&z({t:"health",data:{unhealthy:!0,isDead:!0}})};ja.onmessage=function(e){e&&e.data&&(e=JSON.parse(e.data),e.hb?h({hb:!0}):e.end?close():z(e))}}catch(Aa){w.reject(Aa),w=null}return ia.promise}function w(){ca&&z&&n(z);return x.promise}var x=window.createPromiseCapability(),y=null,z,ba,aa=null,ca=!1,da=!1,ea=e,fa=function(e){var f=e.indexOf("://"),h="ws://";0>f?f=0:(5===f&&(h="wss://"),f+=3);var n=e.lastIndexOf("/");0>n&&(n=e.length);
return h+e.slice(f,n)}(f);return{send:h,iD:n,mA:function(){return y?y.promise:w().then(function(e){y=window.createPromiseCapability();z=null;e.close();return y.promise})},clientId:r}}function w(f){var e=f.lastIndexOf("/");0>e&&(e=f.length);return f.slice(0,e)}var r=ba(8);return window.WebSocket&&!y?x(f,z,r):function(f,e,r){function h(e){(ca?ca.promise:Promise.resolve(aa)).then(function(f){var h=new XMLHttpRequest;f=ba?z+"/"+ba+"pf?id="+f:z+"/pf?id="+f;f+="&bcid="+r;var n=new FormData;n.append("data",
JSON.stringify(e));h.open("POST",f);h.withCredentials=!0;h.send(n)})}function n(){aa=0;ca||(ca=window.createPromiseCapability())}function x(){y=new XMLHttpRequest;var e=z+"/pf";e=0!==aa?e+("?id="+aa+"&uc="+ja):e+("?uc="+ja);ja++;y.open("GET",e,!0);y.withCredentials=!0;y.setRequestHeader("Cache-Control","no-cache");y.setRequestHeader("X-Requested-With","XMLHttpRequest");var f=y,r=!1;y.onreadystatechange=function(){a:if(3<=f.readyState&&!r){try{var e=f.responseText.length}catch(Ba){Object(fa.f)("caught exception");
break a}if(0<e)try{var w=f.responseText.split("\n");for(w[w.length-1]&&w.pop();0<w.length&&3>w[w.length-1].length;)"]"===w.pop()&&n();0<w.length&&3>w[0].length&&w.shift();for(e=0;e<w.length;++e)w[e].endsWith(",")&&(w[e]=w[e].substr(0,w[e].length-1));0===aa&&0<w.length&&(aa=JSON.parse(w.shift()).id,e=ca,ca=null,e.resolve(aa));var y;for(e=0;e<w.length;++e)(y=JSON.parse(w[e]))&&y.end?close():y&&y.hb&&y.id===aa?h({hb:!0}):ha(y)}catch(Ba){}da||(r=!0,x())}};y.send()}var y,z=w(f),ba=e,aa=0,ca=window.createPromiseCapability(),
da=!1,ea=null,ha=null,ja=0;return{send:h,iD:function(e,f,h){ha=e;ea=h;da=!1;n();x();f&&f();return Promise.resolve()},mA:function(){n();ha=null;da=!0;ea&&ea();y.abort();return Promise.resolve()},clientId:r}}(f,z,r)}f.d(da,"a",function(){return ea});var fa=f(1)}}]);}).call(this || window)
