/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{327:function(ha,da,f){f.r(da);f.d(da,"ByteRangeRequest",function(){return ka});var ba=f(3),ea=f(0);f.n(ea);var fa=f(1),aa=f(109);ha=f(71);var z=f(137),y=f(61),x=f(51),w=f(184),r=f(124);f=f(280);var n=[],e=[],ca=window,h=function(){return function(){this.Oj=1}}(),ia;(function(e){e[e.UNSENT=0]="UNSENT";e[e.DONE=4]="DONE"})(ia||(ia={}));var ka=function(){function f(e,f,h,n){var r=this;this.url=e;this.range=f;this.sf=h;this.withCredentials=
n;this.ZO=ia;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);ca.Uint8Array&&(this.request.responseType="arraybuffer");n&&(this.request.withCredentials=n);oa.DISABLE_RANGE_HEADER||(Object(ea.isUndefined)(f.stop)?this.request.setRequestHeader("Range","bytes="+f.start):this.request.setRequestHeader("Range",["bytes=",f.start,"-",f.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");h&&Object.keys(h).forEach(function(e){r.request.setRequestHeader(e,
h[e])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=w.a.NOT_STARTED}f.prototype.start=function(e){var f=this,h=this.request;h.onreadystatechange=function(){if(f.aborted)return f.status=w.a.ABORTED,e({code:w.a.ABORTED});if(this.readyState===f.ZO.DONE){f.Sv();var n=0===window.document.URL.indexOf("file:///");200===h.status||206===h.status||n&&0===h.status?(n=ca.XI(this),
f.Dp(n,e)):(f.status=w.a.ERROR,e({code:f.status,status:this.status}))}};this.request.send(null);this.status=w.a.STARTED};f.prototype.Dp=function(e,f){this.status=w.a.SUCCESS;if(f)return f(!1,e)};f.prototype.abort=function(){this.Sv();this.aborted=!0;this.request.abort()};f.prototype.Sv=function(){var h=Object(r.b)(this.url,this.range,e);-1!==h&&e.splice(h,1);if(0<n.length){h=n.shift();var w=new f(h.url,h.range,this.sf,this.withCredentials);h.request=w;e.push(h);w.start(Object(r.c)(h))}};f.prototype.extend=
function(e){var f=Object.assign({},this,e.prototype);f.constructor=e;return f};return f}(),oa=function(f){function w(e,h,n,r,w){n=f.call(this,e,n,r)||this;n.Qj={};n.Nu=h;n.url=e;n.DISABLE_RANGE_HEADER=!1;n.zs=ka;n.bE=3;n.sf=w||{};return n}Object(ba.c)(w,f);w.prototype.Nq=function(e,f,h){var n=-1===e.indexOf("?")?"?":"&";switch(h){case !1:case x.a.NEVER_CACHE:e=e+n+"_="+Object(ea.uniqueId)();break;case !0:case ["CacheHinting.CACHE"]:e=e+n+"_="+f.start+","+(Object(ea.isUndefined)(f.stop)?"":f.stop)}return e};
w.prototype.oH=function(e,f,h,n){void 0===h&&(h={});return new this.zs(e,f,h,n)};w.prototype.$T=function(f,h,r,w,x){for(var y=0;y<n.length;y++)if(Object(ea.isEqual)(n[y].range,h)&&Object(ea.isEqual)(n[y].url,f))return n[y].Nf.push(w),n[y].Lw++,null;for(y=0;y<e.length;y++)if(Object(ea.isEqual)(e[y].range,h)&&Object(ea.isEqual)(e[y].url,f))return e[y].Nf.push(w),e[y].Lw++,null;r={url:f,range:h,Nu:r,Nf:[w],Lw:1};if(0===n.length&&e.length<this.bE)return e.push(r),r.request=this.oH(f,h,x,this.withCredentials),
r;n.push(r);return null};w.prototype.$k=function(f,h,w){var x=this.Nq(f,h,this.Nu);(f=this.$T(x,h,this.Nu,w,this.sf))&&f.request.start(Object(r.c)(f));return function(){var f=Object(r.b)(x,h,e);if(-1!==f){var w=--e[f].Lw;0===w&&e[f].request&&e[f].request.abort()}else f=Object(r.b)(x,h,n),-1!==f&&(w=--n[f].Lw,0===w&&n.splice(f,1))}};w.prototype.DI=function(){return{start:-aa.a}};w.prototype.tW=function(){var e=-(aa.a+aa.e);return{start:e-aa.d,end:e}};w.prototype.Uo=function(e){var f=this;this.Su=!0;
var h=aa.a;this.$k(this.url,this.DI(),function(n,r,w){function x(){var h=f.ud.AI();f.$k(f.url,h,function(n,r){if(n)return Object(fa.h)("Error loading central directory: "+n),e(n);r=Object(y.a)(r);if(r.length!==h.stop-h.start)return e("Invalid XOD file: Zip central directory data is wrong size! Should be "+(h.stop-h.start)+" but is "+r.length);f.ud.aL(r);f.Jz=!0;f.Su=!1;return e(!1)})}if(n)return Object(fa.h)("Error loading end header: "+n),e(n,r,w);r=Object(y.a)(r);if(r.length!==h)return e("Invalid XOD file: Zip end header data is wrong size!");
try{f.ud=new z.a(r)}catch(wa){return e(wa)}f.ud.FX?f.$k(f.url,f.tW(),function(h,n){if(h)return Object(fa.h)("Error loading zip64 header: "+h),e(h);n=Object(y.a)(n);f.ud.UX(n);x()}):x()})};w.prototype.TI=function(e){e(Object.keys(this.ud.Ik))};w.prototype.lC=function(e,f){var n=this;if(this.ud.gH(e)){var r=this.ud.Lv(e);if(r in this.Qj){var w=this.Dg[e];w.fo=this.Qj[r];w.fo.Oj++;w.cancel=w.fo.cancel}else{var x=this.ud.aV(e),y=this.$k(this.url,x,function(h,w){h?(Object(fa.h)('Error loading part "'+
e+'": '+h),n.$k(n.url,x,function(h,w){if(h)return f(h,e);n.bL(w,x,r,e,f)})):n.bL(w,x,r,e,f)}),ca=this.Dg[e];ca&&(ca.HM=!0,ca.cancel=function(){ca.fo.Oj--;0===ca.fo.Oj&&(y(),delete n.Qj[r])},this.Qj[r]=new h(r),ca.fo=this.Qj[r],ca.fo.cancel=ca.cancel)}}else delete this.Dg[e],f(Error('File not found: "'+e+'"'),e)};w.prototype.bL=function(e,f,h,n,r){if(e.length!==f.stop-f.start)r(Error("Part data is wrong size!"),n);else{do{if(!this.Qj[h])return;n=this.Qj[h].Oj;for(var w=f.$K.length,x=0;x<w;++x){var y=
f.$K[x];r(!1,y.Um,e["string"===typeof e?"substring":"subarray"](y.start,y.stop),this.ud.KJ(y.Um));y.Um in this.Dg&&delete this.Dg[y.Um]}}while(n!==this.Qj[h].Oj);delete this.Qj[h]}};w.DISABLE_RANGE_HEADER=!1;w.bE=3;return w}(ha.a);(function(e){function f(f,h,n){var r=e.call(this)||this,w;for(w in f)r[w]=f[w];r.l4=f;r.startOffset=h;r.endOffset=n;r.oH=function(e,h,n,w){Object(ea.isUndefined)(h.stop)?(h.start+=r.endOffset,h.stop=r.endOffset):(h.start+=r.startOffset,h.stop+=r.startOffset);e=r.Nq(r.url,
h,r.Nu);return new f.zs(e,h,n,w)};return r}Object(ba.c)(f,e);return f})(oa);Object(f.a)(oa);Object(f.b)(oa);da["default"]=oa}}]);}).call(this || window)
