/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[10],{344:function(ha,da,f){function ba(e){e.Aa();e.advance();var f=e.current.textContent;e.Ra();return f}function ea(e){var f=[];for(e.Aa();e.advance();){var h=e.Ha();"field"===h?f.push(String(e.aa("name"))):Object(ia.h)("unrecognised field list element: "+h)}e.Ra();return f}function fa(e,f){return f?"false"===e?!1:!0:"true"===e?!0:!1}function aa(e,f){var h=e.Ha();switch(h){case "javascript":return{name:"JavaScript",javascript:e.current.textContent};
case "uri":return{name:"URI",uri:e.aa("uri")};case "goto":h=null;e.Aa();if(e.advance()){var n=e.aa("fit");h={page:e.aa("page"),fit:n};if("0"===h.page)Object(ia.h)("null page encountered in dest");else switch(f=f(Number(h.page)),n){case "Fit":case "FitB":break;case "FitH":case "FitBH":h.top=f.ha({x:0,y:e.aa("top")||0}).y;break;case "FitV":case "FitBV":h.left=f.ha({x:e.aa("left")||0,y:0}).x;break;case "FitR":n=f.ha({x:e.aa("left")||0,y:e.aa("top")||0});f=f.ha({x:e.aa("right")||0,y:e.aa("bottom")||0});
f=new xa.a(n.x,n.y,f.x,f.y);h.top=f.ca;h.left=f.fa;h.bottom=f.da;h.right=f.ga;break;case "XYZ":n=f.ha({x:e.aa("left")||0,y:e.aa("top")||0});h.top=n.y;h.left=n.x;h.zoom=e.aa("zoom")||0;break;default:Object(ia.h)("unknown dest fit: "+n)}h={name:"GoTo",dest:h}}else Object(ia.h)("missing dest in GoTo action");e.Ra();return h;case "submit-form":h={name:"SubmitForm",url:e.aa("url"),format:e.aa("format"),method:e.aa("method")||"POST",exclude:fa(e.aa("exclude"),!1)};f=e.aa("flags");h.flags=f?f.split(" "):
[];for(e.Aa();e.advance();)switch(f=e.Ha(),f){case "fields":h.fields=ea(e);break;default:Object(ia.h)("unrecognised submit-form child: "+f)}e.Ra();return h;case "reset-form":h={name:"ResetForm",exclude:fa(e.aa("exclude"),!1)};for(e.Aa();e.advance();)switch(f=e.Ha(),f){case "fields":h.fields=ea(e);break;default:Object(ia.h)("unrecognised reset-form child: "+f)}e.Ra();return h;case "hide":h={name:"Hide",hide:fa(e.aa("hide"),!0)};for(e.Aa();e.advance();)switch(f=e.Ha(),f){case "fields":h.fields=ea(e);
break;default:Object(ia.h)("unrecognised hide child: "+f)}e.Ra();return h;case "named":return{name:"Named",action:e.aa("name")};default:Object(ia.h)("Encountered unexpected action type: "+h)}return null}function z(e,f,h){var n={};for(e.Aa();e.advance();){var r=e.Ha();switch(r){case "action":r=e.aa("trigger");if(f?-1!==f.indexOf(r):1){n[r]=[];for(e.Aa();e.advance();){var w=aa(e,h);Object(ka.isNull)(w)||n[r].push(w)}e.Ra()}else Object(ia.h)("encountered unexpected trigger on field: "+r);break;default:Object(ia.h)("encountered unknown action child: "+
r)}}e.Ra();return n}function y(e){return new ma.a(e.aa("r")||0,e.aa("g")||0,e.aa("b")||0,e.aa("a")||1)}function x(e,f){var h=e.aa("name"),n=e.aa("type")||"Type1",r=e.aa("size"),w=f.ha({x:0,y:0});r=f.ha({x:Number(r),y:0});f=w.x-r.x;w=w.y-r.y;h={name:h,type:n,size:Math.sqrt(f*f+w*w)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(e.Aa();e.advance();)switch(n=e.Ha(),n){case "stroke-color":h.strokeColor=y(e);break;case "fill-color":h.fillColor=y(e);break;default:Object(ia.h)("unrecognised font child: "+
n)}e.Ra();return h}function w(e){return{value:e.aa("value"),displayValue:e.aa("display-value")||void 0}}function r(e){var f=[];for(e.Aa();e.advance();){var h=e.Ha();switch(h){case "option":f.push(w(e));break;default:Object(ia.h)("unrecognised options child: "+h)}}e.Ra();return f}function n(e,f){var h=e.aa("name"),n={type:e.aa("type"),quadding:e.aa("quadding")||"Left-justified",maxLen:e.aa("max-len")||-1},w=e.aa("flags");Object(ka.isString)(w)&&(n.flags=w.split(" "));for(e.Aa();e.advance();)switch(w=
e.Ha(),w){case "actions":n.actions=z(e,["C","F","K","V"],function(){return f});break;case "default-value":n.defaultValue=ba(e);break;case "font":n.font=x(e,f);break;case "options":n.options=r(e);break;default:Object(ia.h)("unknown field child: "+w)}e.Ra();return new window.Annotations.ea.ka(h,n)}function e(e,f){switch(e.type){case "Tx":try{if(Object(sa.c)(e.actions))return new oa.a.DatePickerWidgetAnnotation(e,f)}catch(ja){Object(ia.h)(ja)}return new oa.a.TextWidgetAnnotation(e,f);case "Ch":return e.flags.get(ua.WidgetFlags.COMBO)?
new oa.a.ChoiceWidgetAnnotation(e,f):new oa.a.ListWidgetAnnotation(e,f);case "Btn":return e.flags.get(ua.WidgetFlags.PUSH_BUTTON)?new oa.a.PushButtonWidgetAnnotation(e,f):e.flags.get(ua.WidgetFlags.RADIO)?new oa.a.RadioButtonWidgetAnnotation(e,f):new oa.a.CheckButtonWidgetAnnotation(e,f);case "Sig":return new oa.a.SignatureWidgetAnnotation(e,f);default:Object(ia.h)("Unrecognised field type: "+e.type)}return null}function ca(e,f){var h={number:e.aa("number")};for(e.Aa();e.advance();){var n=e.Ha();
switch(n){case "actions":h.actions=z(e,["O","C"],f);break;default:Object(ia.h)("unrecognised page child: "+n)}}e.Ra();return h}function h(f,h,r,w){var aa=[],ba={};f.Aa();var da=[],ja={},fa=[];Object(na.a)(function(){if(f.advance()){var r=f.Ha();switch(r){case "calculation-order":da="calculation-order"===f.Ha()?ea(f):[];break;case "document-actions":ja=z(f,["Init","Open"],h);break;case "pages":r=[];for(f.Aa();f.advance();){var w=f.Ha();switch(w){case "page":r.push(ca(f,h));break;default:Object(ia.h)("unrecognised page child: "+
w)}}f.Ra();fa=r;break;case "field":w=n(f,h(1));ba[w.name]=w;break;case "widget":r={border:{style:"Solid",width:1},backgroundColor:[],fieldName:f.aa("field"),page:f.aa("page"),index:f.aa("index")||0,rotation:f.aa("rotation")||0,flags:[]};(w=f.aa("appearance"))&&(r.appearance=w);(w=f.aa("flags"))&&(r.flags=w.split(" "));for(f.Aa();f.advance();)switch(w=f.Ha(),w){case "rect":var ha=f,ka=h(Number(r.page));w=ka.ha({x:ha.aa("x1")||0,y:ha.aa("y1")||0});ha=ka.ha({x:ha.aa("x2")||0,y:ha.aa("y2")||0});w=new xa.a(w.x,
w.y,ha.x,ha.y);w.normalize();r.rect={x1:w.x1,y1:w.y1,x2:w.x2,y2:w.y2};break;case "border":w=f;ha={style:w.aa("style")||"Solid",width:w.aa("width")||1,color:[0,0,0]};for(w.Aa();w.advance();)switch(ka=w.Ha(),ka){case "color":ha.color=y(w);break;default:Object(ia.h)("unrecognised border child: "+ka)}w.Ra();r.border=ha;break;case "background-color":r.backgroundColor=y(f);break;case "actions":r.actions=z(f,"E X D U Fo Bl PO PC PV PI".split(" "),h);break;case "appearances":w=f;ha=Object(sa.b)(r,"appearances");
for(w.Aa();w.advance();)if(ka=w.Ha(),"appearance"===ka){ka=w.aa("name");var la=Object(sa.b)(ha,ka);ka=w;for(ka.Aa();ka.advance();){var wa=ka.Ha();switch(wa){case "Normal":Object(sa.b)(la,"Normal").data=ka.current.textContent;break;default:Object(ia.h)("unexpected appearance state: ",wa)}}ka.Ra()}else Object(ia.h)("unexpected appearances child: "+ka);w.Ra();break;case "extra":w=f;ha=h;ka={};for(w.Aa();w.advance();)switch(la=w.Ha(),la){case "font":ka.font=x(w,ha(1));break;default:Object(ia.h)("unrecognised extra child: "+
la)}w.Ra();w=ka;w.font&&(r.font=w.font);break;case "captions":ha=f;w={};(ka=ha.aa("Normal"))&&(w.Normal=ka);(ka=ha.aa("Rollover"))&&(w.Rollover=ka);(ha=ha.aa("Down"))&&(w.Down=ha);r.captions=w;break;default:Object(ia.h)("unrecognised widget child: "+w)}f.Ra();(w=ba[r.fieldName])?(r=e(w,r),aa.push(r)):Object(ia.h)("ignoring widget with no corresponding field data: "+r.fieldName);break;default:Object(ia.h)("Unknown element encountered in PDFInfo: "+r)}return!0}return!1},function(){f.Ra();r({calculationOrder:da,
widgets:aa,fields:ba,documentActions:ja,pages:fa,custom:[]})},w)}f.r(da);f.d(da,"parse",function(){return h});var ia=f(1),ka=f(0);f.n(ka);var oa=f(87),xa=f(7),ma=f(8),na=f(80),sa=f(77),ua=f(22)}}]);}).call(this || window)
