/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[12],{336:function(ha,da,f){f.r(da);var ba=f(3),ea=f(0);f.n(ea);var fa=f(1),aa=f(109);ha=f(39);var z=f(71),y=f(137),x=f(51),w=f(184);f=f(280);var r=window,n=function(){function e(e,f,h){var n=-1===e.indexOf("?")?"?":"&";switch(f){case x.a.b2:this.url=e+n+"_="+Object(ea.uniqueId)();break;default:this.url=e}this.sf=h;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=w.a.NOT_STARTED}e.prototype.start=function(f,h){var n=this,r=this,x=this.request,y;r.Ur=0;f&&Object.keys(f).forEach(function(e){n.request.setRequestHeader(e,f[e])});h&&(this.request.withCredentials=h);this.$w=setInterval(function(){var f=0===window.document.URL.indexOf("file:///");f=200===x.status||f&&0===x.status;
if(x.readyState!==w.b.DONE||f){try{x.responseText}catch(ua){return}r.Ur<x.responseText.length&&(y=r.bZ())&&r.trigger(e.Events.DATA,[y]);0===x.readyState&&(clearInterval(r.$w),r.trigger(e.Events.DONE))}else clearInterval(r.$w),r.trigger(e.Events.DONE,["Error received return status "+x.status])},1E3);this.request.send(null);this.status=w.a.STARTED};e.prototype.bZ=function(){var f=this.request,h=f.responseText;if(0!==h.length)if(this.Ur===h.length)clearInterval(this.$w),this.trigger(e.Events.DONE);else return h=
Math.min(this.Ur+3E6,h.length),f=r.XI(f,this.Ur,!0,h),this.Ur=h,f};e.prototype.abort=function(){clearInterval(this.$w);var f=this;this.request.onreadystatechange=function(){Object(fa.h)("StreamingRequest aborted");f.status=w.a.ABORTED;return f.trigger(e.Events.ABORTED)};this.request.abort()};e.prototype.finish=function(){var f=this;this.request.onreadystatechange=function(){f.status=w.a.SUCCESS;return f.trigger(e.Events.DONE)};this.request.abort()};e.Events={DONE:"done",DATA:"data",ABORTED:"aborted"};
return e}();Object(ha.b)(n);var e;(function(e){e[e.LOCAL_HEADER=0]="LOCAL_HEADER";e[e.FILE=1]="FILE";e[e.CENTRAL_DIR=2]="CENTRAL_DIR"})(e||(e={}));var ca=function(f){function h(){var h=f.call(this)||this;h.buffer="";h.state=e.LOCAL_HEADER;h.gD=4;h.Aj=null;h.Yo=aa.c;h.Ik={};return h}Object(ba.c)(h,f);h.prototype.YY=function(f){var n;for(f=this.buffer+f;f.length>=this.Yo;)switch(this.state){case e.LOCAL_HEADER:this.Aj=n=this.eZ(f.slice(0,this.Yo));if(n.wp!==aa.g)throw Error("Wrong signature in local header: "+
n.wp);f=f.slice(this.Yo);this.state=e.FILE;this.Yo=n.Az+n.Pm+n.fr+this.gD;this.trigger(h.Events.HEADER,[n]);break;case e.FILE:this.Aj.name=f.slice(0,this.Aj.Pm);this.Ik[this.Aj.name]=this.Aj;n=this.Yo-this.gD;var r=f.slice(this.Aj.Pm+this.Aj.fr,n);this.trigger(h.Events.FILE,[this.Aj.name,r,this.Aj.Qz]);f=f.slice(n);if(f.slice(0,this.gD)===aa.h)this.state=e.LOCAL_HEADER,this.Yo=aa.c;else return this.state=e.CENTRAL_DIR,!0}this.buffer=f;return!1};h.Events={HEADER:"header",FILE:"file"};return h}(y.a);
Object(ha.b)(ca);ha=function(e){function f(f,h,r,w,x){r=e.call(this,f,r,w)||this;r.url=f;r.stream=new n(f,h);r.ud=new ca;r.QK=window.createPromiseCapability();r.fL={};r.sf=x;return r}Object(ba.c)(f,e);f.prototype.Gs=function(e){var f=this;this.request([this.Ih,this.Ai,this.Hh]);this.stream.on(n.Events.DATA,function(h){try{if(f.ud.YY(h))return f.stream.finish()}catch(ma){throw f.stream.abort(),f.br(ma),e(ma),ma;}});this.stream.on(n.Events.DONE,function(h){f.KY=!0;f.QK.resolve();h&&(f.br(h),e(h))});
this.ud.on(ca.Events.HEADER,Object(ea.bind)(this.eL,this));this.ud.on(ca.Events.FILE,Object(ea.bind)(this.hZ,this));return this.stream.start(this.sf,this.withCredentials)};f.prototype.TI=function(e){var f=this;this.QK.promise.then(function(){e(Object.keys(f.ud.Ik))})};f.prototype.ml=function(){return!0};f.prototype.request=function(e){var f=this;this.KY&&e.forEach(function(e){f.fL[e]||f.c1(e)})};f.prototype.eL=function(){};f.prototype.abort=function(){this.stream&&this.stream.abort()};f.prototype.c1=
function(e){this.trigger(z.a.Events.PART_READY,[{Ta:e,error:"Requested part not found",Vg:!1,qf:!1}])};f.prototype.hZ=function(e,f,h){this.fL[e]=!0;this.trigger(z.a.Events.PART_READY,[{Ta:e,data:f,Vg:!1,qf:!1,error:null,Hc:h}])};return f}(z.a);Object(f.a)(ha);Object(f.b)(ha);da["default"]=ha}}]);}).call(this || window)
